services:
  inventorydb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5732:5432
    volumes:
      - ./db:/var/lib/postgresql/data